#!/usr/bin/env bash

#-- Version: 1.0
#-- Author: Enrico Spinielli
#-- Date: 2016/09/22
#-- Copyright (C) 2016 Eurocontrol/PRU


##- Usage: extract_monthly_data [-f filename] WEF TIL
##- Extract En-Route ATFM Delay (FIR based) data to csv file for the interval [WEF, TIL).
##- WEF and TIL format is: YYYYMM, i.e. 201503 (Mar 2015)
##- Note: TIL is _not_ included.
##-
##- Assumptions:
##-   DBUSR                   environment variable for the relevant schema username.
##-   DBPWD                   environment variable for the relevant schema password.
##-   DBNAME                  environment variable for the relevant schema name.
##-
##-
##- Options:
##-   -f, --file filename     The name of the file to save the output to (default 'ert_dly_<WEF YEAR><WEF MONTHNUM>.csv').
##-   -h, --help              Print a usage message summarizing the command-line options, then exit.
##-   -V, --version           Output version information and exit.
##-
##- Examples:
##- To extract Jan, Feb and March 2016:
##- $ extract_monthly_data '201601' '201604'
##-
##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)


SCRIPT=$(basename ${BASH_SOURCE[0]})
OUTPUT_FILENAME=''

help=$(grep "^##-" ${BASH_SOURCE} | cut -c 4-)
version=$(grep "^#--"  "${BASH_SOURCE}" | cut -c 4-)
opt_h() {
    echo "$help"
}

opt_v() {
    echo "$version"
}


# Execute getopt
TEMP=$(getopt -o :hV --long ":help,version" -n "$SCRIPT" -- "$@");
eval set -- "$TEMP"

while true; do
    case "$1" in
        -h|--help)
            opt_h
            exit 2
            ;;
        -V|--version)
            opt_v
            exit 2
            ;;
        --)
            shift
            break
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            opt_h
            exit 1
            ;;
        *)
            echo "Internal error!"
            exit 1
            ;;
    esac
done

# there are two mandatory arguments
if (( $# != 2 )); then
    echo "Error: illegal number of parameters"
    opt_h
    exit 1
else
    WEF=$(date --date="${1}01" +"%Y%m%d")
    if [ -z $WEF ]
    then
        echo "Error: invalid WEF"
        opt_h
        exit 1
    else
        declare -ri WEF_YYYY=$(( $(date --date=$WEF +"%Y") ))
        declare -ri WEF_MMMM=$(( $(date --date=$WEF +"%m") ))
    fi

    TIL=$(date --date="${2}01" +"%Y%m%d")
    if [ -z $TIL ]
    then
        echo "Error: invalid TIL"
        opt_h
        exit 1
    else
        declare -ri TIL_YYYY=$(( $(date --date=$TIL +"%Y") ))
        declare -ri TIL_MMMM=$(( $(date --date=$TIL +"%m") ))
    fi
fi

ts="$WEF"
while [ "$ts" != "$TIL" ]; do
    next=$(date -d "$ts +1 month" "+%Y%m%d")
    echo $ts $next
    extract_enroute_atfm_delay_fir_data $ts $next
    ts=$next
done
