# from http://stackoverflow.com/a/27400343/963575
url: "http://localhost:4000"
baseurl: ""
dev: true
assets:
  debug: true
  cache: false

exclude: [Gemfile, Gemfile.lock, README.md, references.bib, tmp, generate_reference.sh,
          dashboard/REAME.md, dashboard/Makefile, dashboard, deploy.sh,
          node_modules, package.json, npm-debug.log, Gruntfile.js]