---
title: "Welcome to the European ANS Performance Data Portal"
date: 2018-02-07T11:26:51+01:00
---

The [Performance Review Unit (PRU)](/about/) has developed 
an online ANS performance data portal covering all 41 EUROCONTROL Member States:

* to ensure that interested stakeholders in all Member States have relevant high quality information
  on Pan-European ANS performance readily available in a transparent, accurate, clear, complete and
  unbiased manner;
* to stimulate an informed dialogue between all stakeholders for the benefit of the entire aviation
  network; and,
* to further develop the ANS performance analysis framework and the understanding of key ANS
  performance issues.

Within the context of Single European Sky (SES), the PRU has developed a dedicated
[SES e-dashboard](http://www.eurocontrol.int/prudata/dashboard/rp2_2017.html)
for the European Commission which is a formal and official source of data in the context of the SES
legislation, supporting NSA’s in their SES monitoring activities.
The PRU updates this data on behalf of the European Commission on a quarterly basis.

