---
title: To Do's
layout: default
---

This is what needs to be checked for full migration to Hugo:

* ~~finish to port acronyms: from "n"~~
* ~~port definitions~~
* ~~bibliography via Rmd~~ but also check [this](https://github.com/mtbhomer/web-portfolio/blob/master/themes/mtbhomer-portfolio/layouts/research/single.html) for publication list solution. It shows as in [here](https://www.mtbhomer.com/research/)
* pagination of posts. Keep only the last 5 or so
* D3 logo: include the fancy logo in the template.
* Improve `howbuilt`
* style header, fonts,...
* custom 404 page
* anti-spammer subscriber
* fix links to CSV download in dataset definitions
* fix table extent in data download page
* clean dashboard layout, i.e. google charst, pym.js,...
* fixed nav bar
* replace favicons with proper shortcodes
* dataset HFE: fix Pym iframe height
* fix "APT DLY filter and CSV download" link, http://localhost:8000/reference/dataset/airport-arrival-atfm-delay/
  in http://localhost:8000/reference/dataset/airport-arrival-atfm-delay/
* should 'crt_ertfltsMM_15.js' be deleted?
* pages for filtered CSV download: do we move?
* consider using excerpt in yaml for list of studies (it gives a sort of summary of the thing)



## New stuff

* generate yearly CSV for HFE, APT_DLY,... (see export<>.R scripts)
* investigate use of http://tachyons.io/
* use ggplotly for graphs
* check htmlwidgets: http://gallery.htmlwidgets.org/ and blogdown
