#!/usr/bin/env bash

#-- Version: 1.0
#-- Author: Enrico Spinielli
#-- Date: 2016/09/22
#-- Copyright (C) 2016 Eurocontrol/PRU


##- Usage: extract_monthly_data [-f filename] WEF TIL
##- Extract En-Route ATFM Delay (FIR based) data to csv file for the interval [WEF, TIL).
##- WEF and TIL format is: YYYYMM, i.e. 201503 (Mar 2015)
##- Note: TIL is _not_ included.
##-
##- Assumptions:
##-   DBUSR                   environment variable for the relevant schema username.
##-   DBPWD                   environment variable for the relevant schema password.
##-   DBNAME                  environment variable for the relevant schema name.
##-
##-
##- Options:
##-   -f, --file filename     The name of the file to save the output to (default 'ert_dly_<WEF YEAR><WEF MONTHNUM>.csv').
##-   -h, --help              Print a usage message summarizing the command-line options, then exit.
##-   -V, --version           Output version information and exit.
##-
##- Examples:
##- To extract Jan, Feb and March 2016:
##- $ extract_monthly_data '201601' '201604'
##-
##- Caveat: be sure to use gnu-getopt and not OSX builtin or Git Bash missing one ;-)


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT=$(basename "${SCRIPT_DIR}/${BASH_SOURCE[0]}")

opt_h() {
    help=$(grep "^##-" "${SCRIPT_DIR}"/"${SCRIPT}" | cut -c 4-)
    echo "$help"
}

opt_v() {
    version=$(grep "^#--"  "${SCRIPT_DIR}/${SCRIPT}" | cut -c 4-)
    echo "$version"
}


# Execute getopt
TEMP=$(getopt -o :hV --long ":help,version" -n "$SCRIPT" -- "$@");

if [ $? != 0 ]
then
    echo "Invalid option(s): $*" >&2
    exit 1
fi

eval set -- "$TEMP"
unset TEMP

while true; do
    case "$1" in
        -h|--help)
            opt_h
            exit 2
            ;;
        -V|--version)
            opt_v
            exit 2
            ;;
        --)
            shift
            break
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            opt_h
            exit 1
            ;;
        *)
            echo "Internal error!"
            exit 1
            ;;
    esac
done

# there are two mandatory arguments
if (( $# != 2 )); then
    echo "Error: illegal number of parameters"
    opt_h
    exit 1
else
    WEFTIL_FORMAT="^[0-9][0-9][0-9][0-9][0-9][0-9]$"

    # test WEF is of correct format
    if [[ ! ($1 =~ $WEFTIL_FORMAT) ]]
    then
        echo "Error: WEF is not a 6-digit number"
        opt_h
        exit 1
    fi

    WEF=$(date --date="${1}01" +"%Y%m%d" 2>/dev/null)
    if [ -z "$WEF" ]
    then
        echo "Error: invalid WEF"
        opt_h
        exit 1
    fi

    # test TIL is of correct format
    if [[ ! ($2 =~ $WEFTIL_FORMAT) ]]
    then
        echo "Error: TIL is not a 6-digit number"
        opt_h
        exit 1
    fi

    TIL=$(date --date="${2}01" +"%Y%m%d" 2>/dev/null)
    if [ -z "$TIL" ]
    then
        echo "Error: invalid TIL = $TIL"
        opt_h
        exit 1
    fi

    (( "$WEF" > "$TIL" )) && echo "Error: WEF > TIL" && exit 1

fi

beg="$WEF"
while (( "$beg" < "$TIL" )); do
    next=$(date -d "$beg +1 month" "+%Y%m%d")

    YYYY=$(date --date="$beg" +"%Y")
    MMMM=$(date --date="$beg" +"%m")

    OUTPUT_FILENAME="ert_flt_${YYYY}${MMMM}.csv"
    extract_en-route_traffic_data -f "$OUTPUT_FILENAME" "$beg" "$next"

    OUTPUT_FILENAME="ert_flt_fab_fir_${YYYY}${MMMM}.csv"
    extract_en-route_traffic_fab_fir_data -f "$OUTPUT_FILENAME" "$beg" "$next"
    beg=$next
done
