---
title: Additional ASMA Time
categories:
  - metadata
  - definition
type: definition
slug: additional-asma-time
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```

The Additional ASMA time is the difference between the actual ASMA transit time
and the unimpeded ASMA time calculated for non-congested conditions.

## Unit of Measurement
Minute.

## Calculation of the indicator
Let

* $c$, a combination of aircraft class, ASMA sectors and arrival runway, as
  described in the technical note for
  [unimpeded ASMA time](`r htmltools::HTML("{{< relref \"/definition/unimpeded-asma-time.md\" >}}")`),
* $f(c)$, a flight characterised by a combination $c$,
* $\textrm{AcASMA}(f(c))$, the actual
  [ASMA transit time](`r htmltools::HTML("{{< relref \"/definition/asma-transit-time.md\" >}}")`)
  for a flight $f(c)$, i.e. the
  elapsed time between the last entry of the flight $f(c)$ in its ASMA sector and
  its actual landing time ([ALDT](`r htmltools::HTML("{{< relref \"/acronym/aldt.md\" >}}")`)),
* $\textrm{UASMA}(c)$, the
  [unimpeded ASMA time](`r htmltools::HTML("{{< relref \"/definition/unimpeded-asma-time.md\" >}}")`)
  for a combination $c$.

The *additional ASMA time*, $\textrm{AdASMA}(f(c))$, is calculated for each flight $f(c)$
as the difference between the actual ASMA transit time $\textrm{AcASMA}(f(c))$ of the
flight and the unimpeded ASMA time $\textrm{UASMA}(c)$:

$$
\textrm{AdASAM}(f(c)) = \textrm{AcASMA}(f(c)) - \textrm{UASMA}(c)
$$

The additional ASMA time, $\textrm{AdASMA}(c)$, for a given combination $c$ is the
average of the additional ASMA time, $\textrm{AdASMA}(f(c))$ of all the flight $f(c)$
characterised by that combination $c$.

The additional ASMA time, $\textrm{AdASMA}$, for a given airport is the weighted
average of the additional ASMA time, $\textrm{AdASMA}(c)$, for all the combinations
$c$ at that airport with their probability of occurrence.

## See also

[Additional ASMA time methodology](`r htmltools::HTML("{{< relref \"/methodology/additional-asma-time-pi\" >}}")`)
