---
title: ASMA Additional Time Dataset
categories:
  - metadata
  - dataset
type: dataset
slug: asma-additional-time
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```


## Data description
The [additional ASMA time](/reference/definition/additional-asma-time/)
is a proxy for the average arrival runway queuing time on the inbound traffic flow,
during congestion periods at airports.

It is the difference between the actual
[ASMA](/reference/acronym/asma/)
time of a flight and a statistically determined
[unimpeded ASMA time](/reference/definition/unimpeded-asma-time/)
based on ASMA times in periods of low traffic demand.

When monitoring ASMA performance at airports, it is important to note that the
goal is not to reduce ASMA time to the unimpeded reference time - as this could
negatively impact on runway throughput - but rather to reduce additional ASMA
time and associated fuel burnt to the necessary minimum.

## Column naming and types

| Column name       | Data source     | Label       | Column description                                                  | Example  |
|-------------------|-----------------|-------------|---------------------------------------------------------------------|----------|
| YEAR              | Network Manager | YEAR        | Reference year                                                      | 2014     |
| MONTH_NUM         | Network Manager | MONTH       | Month (numeric)                                                     | 1        |
| MONTH_MON         | Network Manager | MONTH_MON   | Month (3-letter code)                                               | JAN      |
| APT_ICAO          | PRU             | APT_ICAO    | ICAO 4-letter airport designator                                    | EBBR     |
| APT_NAME          | PRU             | APT_NAME    | Airport name                                                        | Brussels |
| STATE_NAME        | PRU             | STATE_NAME  | Country in which the airport is located                             | Belgium  |
| ASMA_RADIUS       | PRU             | ASMA_RADIUS | The radius around the airport (in NM) used for the ASMA calculation | 40       |
| FLT_ASMA_UNIMP_2  | NM_Airport      |             | IFR flights with unimpeded reference time                           | 7290     |
| TIME_ASMA_UNIMP_2 | NM_Airport      |             | Total unimpeded reference ASMA time in minutes                      | 60081    |
| TIME_ASMA_ADD_2   | NM_Airport      |             | Total additional ASMA time in minutes                               | 15175    |


### Calculated Field(s)

$$
\begin{align*}
\text{Average additional ASMA time} & = \frac{\text{TIME_ASMA_ADD_2}}{\text{FLT_ASMA_UNIMP_2}} 
\end{align*}
$$

$$
\begin{align*}
\text{Average unimpeded ASMA time} & = \frac{\text{TIME_ASMA_UNIMP_2}}{\text{FLT_ASMA_UNIMP_2}}
\end{align*}
$$
