---
title: "En-route ATFM Delays"
author: "Enrico Spinielli"
date: "22 November 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=TRUE, cache=FALSE}
library(knitr)
# Remember to run read_ert_flt.R

# Remember to run ert_dly.R
read_chunk("ert_dly.R")
```

## Timeseries

Time series of average en-route ATFM delay on a yearly basis
```{r fir_ert_dly_ts}
library(ggplot2)
g <- ggplot(fab_dd, aes(date, avg_dd)) +
  geom_line() + scale_x_date(date_labels = "%b-%Y", date_minor_breaks = "1 month") +
  facet_wrap(~entity_name, nrow = 5) +
  labs(title = "Average Daily En-route ATFM Delay",
       y = "Average Delay (min/flight)") +
  theme(axis.text.x = element_text(angle = 40, hjust = 1))
g
#ggsave("R/avg_delay_per_fab.png")

```

There are few interesting peaks: let's check Aug 2016!

```{r fir_ert_dly_201608}
fff <- fab_dd %>%
  filter(between(date, as.Date("2016-08-01"), as.Date("2016-08-31")))
g <- ggplot(fff, aes(date, avg_dd)) +
  geom_line() + scale_x_date(date_labels = "%d-%b", date_minor_breaks = "1 day") +
  facet_wrap(~entity_name, nrow = 5) +
  labs(title = "Average Daily En-route ATFM Delay: Aug 2016",
       y = "Average Delay (min/flight)") +
  theme(axis.text.x = element_text(angle = 40, hjust = 1))

# annotate SW FAB plot: 23rd Aug 2016
ddd <- fab_dd %>% 
  filter(between(date, as.Date("2016-08-23"), as.Date("2016-08-23"))) %>%
  filter((entity_name %in% c("SW FAB") & delay_type == "C"))
g <- g + 
  geom_point(data = ddd) +
  geom_text(data = ddd, label = "Strike (Spain)", hjust = 1, nudge_x = 0.1)
g
#ggsave("R/spain_strike_aug_2016.png")

```


## Yearly delays per tpe of delay

Let's plot things for France...

```{r france_ert_dly_causes}
fr_dly <- continental_yy %>% filter(entity_name == "France")

g <- ggplot(fr_dly, aes(yyyy, avg_dly_yy)) +
  geom_bar(stat="identity", aes(fill = delay_type)) +
  labs(title = "Yearly Average Daily En-route ATFM Delay: France")
g
#ggsave("R/yearly_avg_delay_cause_France.png")

```

```{r fir_ert_dly_causes}
g <- ggplot(continental_dly_type_yy, aes(yyyy, delay_flt)) +
  geom_bar(stat="identity", aes(fill = delay_type)) +
  labs(title = "Yearly Average Daily En-route ATFM Delays: (continental) States")


#ggsave("R/yearly_avg_delay_cause_Continental.png")


```